  api/activate-user[m
  api/auth[m
  api/category[m
  api/customer[m
  api/dashboard[m
  api/login-google[m
  api/notification[m
  api/product[m
  api/product-image[m
  api/product-supplier[m
  api/sale[m
  api/stock[m
  api/stock-movement[m
  api/suppplier[m
  api/units[m
  api/user[m
  bug/active-link[m
  db/product-supplier[m
  feature/acitvateStaffAccount[m
  feature/mail[m
  feature/pagination[m
  fix/api-constant[m
  fix/auth[m
  fix/auth-frontend[m
  fix/authValidation[m
  fix/category[m
  fix/category-update-api[m
  fix/clean-code[m
  fix/cors[m
  fix/db[m
  fix/exception[m
  fix/notification[m
  fix/readme[m
  fix/reset-password[m
  fix/socket[m
  fix/userMapper[m
  fix/validation[m
  main[m
* [32moptimization[m
