spring.application.name=smart-inventory-system
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

server.port=5000

jwt.secret=${JWT_SECRET}

# Auth Database
auth.datasource.jdbc-url=jdbc:mysql://localhost:3306/SmartInventoryAuthDB
auth.datasource.username=root
auth.datasource.password=password
auth.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SIMS Database
sims.datasource.jdbc-url=jdbc:mysql://localhost:3306/SmartInventoryDB
sims.datasource.username=root
sims.datasource.password=password
sims.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.show-sql=true

#HikariCP configuration(30/10/30)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

cloudinary.cloud_name= ${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key = ${CLOUDINARY_API_KEY}
cloudinary.api_secret = ${CLOUDINARY_API_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
